/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as RouteGuideRouteImport } from './routes/route-guide'
import { Route as RouteEndRouteImport } from './routes/route-end'
import { Route as RecordRouteImport } from './routes/record'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ExploreRouteImport } from './routes/explore'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteGuideRoute = RouteGuideRouteImport.update({
  id: '/route-guide',
  path: '/route-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteEndRoute = RouteEndRouteImport.update({
  id: '/route-end',
  path: '/route-end',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/explore': typeof ExploreRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRoute
  '/route-end': typeof RouteEndRoute
  '/route-guide': typeof RouteGuideRoute
  '/stats': typeof StatsRoute
}
export interface FileRoutesByTo {
  '/explore': typeof ExploreRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRoute
  '/route-end': typeof RouteEndRoute
  '/route-guide': typeof RouteGuideRoute
  '/stats': typeof StatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/explore': typeof ExploreRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRoute
  '/route-end': typeof RouteEndRoute
  '/route-guide': typeof RouteGuideRoute
  '/stats': typeof StatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/explore'
    | '/home'
    | '/profile'
    | '/record'
    | '/route-end'
    | '/route-guide'
    | '/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/explore'
    | '/home'
    | '/profile'
    | '/record'
    | '/route-end'
    | '/route-guide'
    | '/stats'
  id:
    | '__root__'
    | '/explore'
    | '/home'
    | '/profile'
    | '/record'
    | '/route-end'
    | '/route-guide'
    | '/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ExploreRoute: typeof ExploreRoute
  HomeRoute: typeof HomeRoute
  ProfileRoute: typeof ProfileRoute
  RecordRoute: typeof RecordRoute
  RouteEndRoute: typeof RouteEndRoute
  RouteGuideRoute: typeof RouteGuideRoute
  StatsRoute: typeof StatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-guide': {
      id: '/route-guide'
      path: '/route-guide'
      fullPath: '/route-guide'
      preLoaderRoute: typeof RouteGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-end': {
      id: '/route-end'
      path: '/route-end'
      fullPath: '/route-end'
      preLoaderRoute: typeof RouteEndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ExploreRoute: ExploreRoute,
  HomeRoute: HomeRoute,
  ProfileRoute: ProfileRoute,
  RecordRoute: RecordRoute,
  RouteEndRoute: RouteEndRoute,
  RouteGuideRoute: RouteGuideRoute,
  StatsRoute: StatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
